name: "arctic"
root: "/home/these/Data/Josue/data/arctic/downloads/data/raw_seqs"
obj_root: "/home/these/Data/Josue/data/arctic/downloads/data/meta/object_vtemplates"
text_root: "/home/these/Data/Josue/data/arctic/downloads/data/description"
data_path: "/home/these/Data/Josue/data/arctic/data.npz"
data_obj_pc_path: "/home/these/Data/Josue/data/arctic/obj.pkl"
balance_weights_path: "/home/these/Data/Josue/data/arctic/balance_weights.pkl"
text_json: "/home/these/Data/Josue/data/arctic/text.json"
t2l_json: "/home/these/Data/Josue/data/arctic/text_length.json"
t2c_json: "/home/these/Data/Josue/data/arctic/text_count.json"
flat_hand: False
max_nframes: 150
data_ratio: 1
augm: False
data_num: 4597
text_num: 161