name: "grab"
root: "/home/these/Data/Josue/grab"
obj_root: "/home/these/Data/Josue/data/grab/processed_object_meshes"
data_path: "/home/these/Data/Josue/data/grab/data.npz"  
#train_data_path: "./data/grab/train.npz"
#test_data_path: "./data/grab/test.npz"
#val_data_path: "./data/grab/val.npz"
data_obj_pc_path: "/home/these/Data/Josue/data/grab/obj.pkl"
balance_weights_path: "/home/these/Data/Josue/data/grab/balance_weights.pkl"
text_json: "/home/these/Data/Josue/data/grab/text.json"
t2l_json: "/home/these/Data/Josue/data/grab/text_length.json"
t2c_json: "/home/these/Data/Josue/data/grab/text_count.json"
flat_hand: True
max_nframes: 150
data_ratio: 1
augm: False
data_num: 1335
text_num: 276
