defaults:
  - dataset: arctic
  - clip: clip
  - diffusion: diffusion
  - mpnet: mpnet
  - seq_cvae: seq_cvae
  - pointfeat: pointfeat
  - contact: contact
  - texthom: texthom
  - refiner: refiner
project_name: "texthom"
batch_size: 32 # 64, 512
shuffle: True
drop_last: True
num_workers: 2
result_show_freq: 5
save_pth_freq: 2000
text: ["Place cappuccino with right hand."]
save_demo: True
save_obj: False
balance_weights: True
fps: 30

hydra:
  run:
    dir: outputs/${texthom.model_name}/
  # output_subdir: null
seed: 42
work_dir: "experiments"
load: false
exp: "experiment1"
save_dir: "saved_models"
optimizer: "optim.Adam"
lr: 0.001
scheduler: "optim.lr_scheduler.ReduceLROnPlateau" 
factor: 0.5  
patience: 5 
threshold: 0.001 
min_lr: 1e-7  
num_epochs: 50
mode: train
